Add edit mode + quick fixes

diff --git a/service_generator b/service_generator
--- a/service_generator
+++ b/service_generator
@@ -97,13 +97,264 @@ export FZF_DEFAULT_OPTS='--color=fg:#f8f8f2,bg:#282a36,hl:#bd93f9 --color=fg+:#f
 
 # Action Scripts
 
+function ReadService {
+    local service_path="$1"
+    local service_file
+    service_file="$(basename "$service_path")"
+    local service_name=${service_file%.service}
+
+    declare -gxA SERVICE=()
+    local section=""
+
+    while read -r line; do
+        # skip empty lines
+        [ -z "$line" ] && continue
+        # skip comments
+        [ "$(expr "$line" : '^ *#.*$')" -gt 0 ] && continue
+
+        # get section name if line is a section header
+        sectionCase="$(expr "$line" : '^\[\(.*\)\]$')"
+        # check if line is a directive and a value/s
+        directiveCase="$(expr "$line" : '^.*=.*$')"
+
+        if [ -n "$sectionCase" ]; then
+            section="$sectionCase"
+        elif [ "$directiveCase" -gt 0 ]; then
+            [ -z "$section" ] && display_error "Directive line without section: $line"
+            IFS='=' read -ra args <<< "$line"
+            SERVICE["$section","${args[0]}"]="${args[1]}"
+        else
+            display_error "Failed to read line: $line" 1
+        fi
+    done < "$service_path"
+
+    # Generate array of service sections
+    ServiceSections
+}
+
+function PrintService {
+    for section in "${SERVICE_SECTIONS[@]}"; do
+        echo -e "${BLUE}[${section}]${RESET}"
+        SectionDirectives "$section"
+        for directive in "${!SECTION_DIRECTIVES[@]}"; do
+            local value="${SECTION_DIRECTIVES[$directive]}"
+            echo -e "${MAGENTA}$directive:\n\t\t${YELLOW}${value}${RESET}\n"
+        done
+        echo
+    done
+}
+
+function ServiceSections {
+    declare -ga SERVICE_SECTIONS=()
+
+    for key in "${!SERVICE[@]}"; do
+        local section
+        section="$(cut -d, -f1 <<< "$key")"
+        [[ "${SERVICE_SECTIONS[*]}" =~ $section ]] && continue
+        SERVICE_SECTIONS[${#SERVICE_SECTIONS[@]}]="$section"
+    done
+}
+
+function SectionDirectives {
+    local section="$1"
+    declare -gxA SECTION_DIRECTIVES=()
+
+    for directive in "${!SERVICE[@]}"; do
+        [ "$(expr "$directive" : "^${section},.*\$")" -eq 0 ] && continue
+        local name
+        local value
+        name="$(expr "$directive" : '^.*,\(.*\)$')"
+        value="${SERVICE[$directive]}"
+        SECTION_DIRECTIVES["$name"]="$value"
+    done
+}
+
+function SelectDirective {
+    # Get section
+    local section
+    section=$(printf "%s\n" "${SERVICE_SECTIONS[@]}" \
+       | fzf -e --header "Select Service Section" --prompt "Section: ")
+    # validate section was selected
+    [ -z "$section" ] && return 1
+
+    # Generate Directives for current selected section
+    SectionDirectives "$section"
+
+    # Get directive
+    local directive
+    directive=$(printf "%s\n" "${!SECTION_DIRECTIVES[@]}" \
+       | fzf -e --header "Select Service Section" --prompt "Section: ")
+    # validate section was selected
+    [ -z "$directive" ] && return 1
+
+    echo "${section},$directive"
+}
+
+function KeySection {
+    local key="$1"
+    cut -d, -f1 <<< "$key"
+}
+
+function KeyDirective {
+    local key="$1"
+    cut -d, -f2 <<< "$key"
+}
+
+function KeyValue {
+    local key="$1"
+    echo "${SERVICE["$key"]}"
+}
+
+function SaveService {
+    local service_path="$1"
+    
+    # Create a temporary file to store the modified service content
+    local temp_file
+    temp_file="$(mktemp)"
+    
+    # Write the modified content to the temporary file
+    for section in "${SERVICE_SECTIONS[@]}"; do
+        echo -e "[${section}]" >> "$temp_file"
+        SectionDirectives "$section"
+        for directive in "${!SECTION_DIRECTIVES[@]}"; do
+            local value="${SECTION_DIRECTIVES[$directive]}"
+            echo -e "${directive}=${value}" >> "$temp_file"
+        done
+        echo >> "$temp_file"
+    done
+
+    # Overwrite the original service file with the modified content
+    if sudo cp "$temp_file" "$service_path"; then
+        display_success "Service file saved: ${service_path}"
+        ReloadSystemD
+    else
+        display_error "Failed to save the service file: ${service_path}" 1
+        return 1
+    fi
+
+    # Cleanup: Remove the temporary file
+    rm -f "$temp_file"
+
+    return 0
+}
+
+function DisplayEditModeHelp {
+    declare -A options=(
+    [List]="List the service file with colored current values"
+    [Show]="Show the value of a key (section,directive) e.g. Unit,Description"
+	[Set]="Select Section,Directive and set its value, set empty value to remove the directive"
+	["Set Manual"]="Use manual key(Section,Directive) to create/set/remove directive"
+    ["Set Current Working Directory"]="Set directive Service,WorkingDirectory to current working directory"
+    ["Set User"]="Set Service,User to the selected user"
+    ["Set Group"]="Set Service,Group to the selected group"
+    ["Set Type"]="Set Service,Type to the selected service types"
+	[Help]="Print this help message"
+	[Reload]="Reload the current service file and discard changes"
+	[Save]="Save the current changes to the service file, Reload SystemD Daemons and return back to the control mode"
+	[Back]="Discard current changes and return back to control mode"
+	[Exit]="Discard current changes and exit the script"
+    )
+
+    echo
+    echo -e "${GREEN}Available Options:${RESET}"
+    for option in "${!options[@]}"; do
+        echo -e "${BLUE}$option:\n\t\t${YELLOW}${options[$option]}${RESET}\n"
+    done
+    echo
+}
+
 function EditService {
     local service_path="$1"
     local service_file
     service_file="$(basename "$service_path")"
     local service_name=${service_file%.service}
 
-    echo "EditService"
+    if ! ReadService "$service_path"; then
+        display_error "Failed to read service file." 1
+        return 1
+    fi
+
+    declare -a options=("List" "Show" "Set" "Set Manual"
+        "Set Current Working Directory"
+        "Set User" "Set Group" "Set Type"
+        "Help" "Reload" "Save" "Back" "Exit")
+
+
+    echo -e "${YELLOW}"
+    select choice in "${options[@]}"; do
+        case "$choice" in
+            List) PrintService | less -SR;;
+            Show)
+                key="$(SelectDirective)"
+                [ -z "$key" ] && continue
+                section="$(KeySection "$key")"
+                directive="$(KeyDirective "$key")"
+                value="$(KeyValue "$key")"
+                echo -e "${BLUE}$section${GREEN},${MAGENTA}$directive${GREEN} = ${YELLOW}$value${RESET}"
+                ;;
+            "Set Manual")
+                local key="Unit,Description"
+
+                while true; do
+                    read -re -p "${MAGENTA}Enter key: ${YELLOW}" -i "$key" key
+                    if ! expr "$key" : '^.*,.*$' > /dev/null 2>&1; then
+                        display_error "Invalid key format: $key" 1
+                        continue
+                    fi
+                    break
+                done
+
+                value="$(KeyValue "$key")"
+                read -re -p "${MAGENTA}Enter value for $key: ${YELLOW}" -i "$value" value
+                echo -en "${RESET}"
+                if [ -n "$value" ]; then
+                    SERVICE[$key]="$value"
+                else
+                    unset "SERVICE[$key]"
+                fi;;
+            Set)
+                local value
+                key=$(SelectDirective)
+                [ -z "$key" ] && continue
+                value="$(KeyValue "$key")"
+                read -re -p "${MAGENTA}Enter value for $key: ${YELLOW}" -i "$value" value 
+                echo -ne "${RESET}"
+                if [ -n "$value" ]; then
+                    SERVICE[$key]="$value"
+                else
+                    unset "SERVICE[$key]"
+                fi;;
+            "Set Current Working Directory")
+                SERVICE["Service,WorkingDirectory"]="$(pwd)";;
+            "Set User")
+                SERVICE["Service,User"]="$(getent passwd \
+                    | cut -d: -f1 \
+                    | fzf -e --header "Select User" --prompt "User: " --query "$(id -un)")";;
+            "Set Group")
+                SERVICE["Service,Group"]="$(getent group \
+                    | cut -d: -f1 \
+                    | fzf -e --header "Select Group" --prompt "Group: " --query "$(id -gn)")";;
+            "Set Type")
+                key="Service,Type"
+                value=$(KeyValue $key)
+                value=${value:-"simple"}
+                service_type=(simple forking oneshot dbus notify)
+                selections="$(printf "%s\n" "${service_type[@]}"\
+                    | fzf -e -m --disabled --header "Select Service Types(use tab for multi selections): $value"\
+                    | tr '\n' '|')"
+                SERVICE[$key]="${selections:0:-1}";;
+            Save) SaveService "$service_path" && break;;
+            Help) DisplayEditModeHelp | less -SR;;
+            Reload) 
+                if ! ReadService "$service_path"; then
+                    display_error "Failed to read service file." 1
+                    break
+                fi;;
+            Back) break;;
+            Exit) exit 0;;
+            *) display_error "Invalid Choice" 1;;
+        esac
+    done
 }
 
 function ShowControlServiceHelp {
@@ -145,8 +396,8 @@ function ControlService {
     local service_name=${service_file%.service}
 
     local options=("Status" "Start" "Stop" "Restart" "Enable" "Disable" "Print"
-        "Logs" "Follow Logs" "Edit" "Help" "Editor" "Remove" "Copy" "Rename"
-        "Create Service" "Select Service" "Back" "Exit")
+        "Logs" "Follow Logs" "Edit" "Editor" "Rename" "Copy" "Remove" "Clipboard"
+        "Create Service" "Select Service" "Help" "Back" "Exit")
 
     # show service status
     systemctl status "$service_file" | head -n 3
